"""Modified Image model Add processing status

Revision ID: 0723b52ac659
Revises: 80f3e0e84f37
Create Date: 2024-07-07 13:42:15.546862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0723b52ac659'
down_revision: Union[str, None] = '80f3e0e84f37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('processing', sa.Boolean(), nullable=True))
    op.alter_column('images', 'aspect_ratio',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'aspect_ratio',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_column('images', 'processing')
    # ### end Alembic commands ###
