"""大改模型，直接扬库x2

Revision ID: 434c1edacff2
Revises: 13eec8828019
Create Date: 2024-06-29 17:05:19.761234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '434c1edacff2'
down_revision: Union[str, None] = '13eec8828019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_author_association')
    op.alter_column('images', 'aspect_ratio',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'aspect_ratio',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=True)
    op.create_table('image_author_association',
    sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], name='image_author_association_author_id_fkey'),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name='image_author_association_image_id_fkey')
    )
    # ### end Alembic commands ###
