"""Edited tag model

Revision ID: 718c3e34ddbc
Revises: e75db90636c5
Create Date: 2024-06-15 21:07:16.041943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '718c3e34ddbc'
down_revision: Union[str, None] = 'e75db90636c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('title', sa.String(), nullable=True))
    op.alter_column('images', 'aspect_ratio',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=True)
    op.drop_column('tags', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('images', 'aspect_ratio',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_column('images', 'title')
    # ### end Alembic commands ###
