"""Edited Image model

Revision ID: 790c5c381e3b
Revises: 4ec0b35035f0
Create Date: 2024-06-16 10:30:24.469495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '790c5c381e3b'
down_revision: Union[str, None] = '4ec0b35035f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('accessable', sa.Boolean(), nullable=True))
    op.add_column('images', sa.Column('uploaded', sa.Boolean(), nullable=True))
    op.alter_column('images', 'aspect_ratio',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'aspect_ratio',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_column('images', 'uploaded')
    op.drop_column('images', 'accessable')
    # ### end Alembic commands ###
