"""Add Crawler model

Revision ID: 799bc67607bf
Revises: fcc958566f6e
Create Date: 2024-06-30 13:00:57.040599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '799bc67607bf'
down_revision: Union[str, None] = 'fcc958566f6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawlers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('crawl_type', sa.Enum('RANKING', 'USER', 'SEARCH', name='crawlertype'), nullable=True),
    sa.Column('status', sa.Enum('WAITING', 'WORKING', 'FINISHED', 'FAILED', name='crawlerstatus'), nullable=True),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('processed_pages', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawlers_id'), 'crawlers', ['id'], unique=False)
    op.alter_column('images', 'aspect_ratio',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'aspect_ratio',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_index(op.f('ix_crawlers_id'), table_name='crawlers')
    op.drop_table('crawlers')
    # ### end Alembic commands ###
