"""Edited tag & image model

Revision ID: 7afb8082d054
Revises: 718c3e34ddbc
Create Date: 2024-06-15 23:45:01.463489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7afb8082d054'
down_revision: Union[str, None] = '718c3e34ddbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('source_id', sa.Integer(), nullable=True))
    op.add_column('images', sa.Column('colors', sa.JSON(), nullable=True))
    op.alter_column('images', 'aspect_ratio',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=True)
    op.drop_column('images', 'colours')
    op.add_column('tags', sa.Column('num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'num')
    op.add_column('images', sa.Column('colours', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('images', 'aspect_ratio',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_column('images', 'colors')
    op.drop_column('images', 'source_id')
    # ### end Alembic commands ###
