"""Add aspect_ratio

Revision ID: 9a6d035ec9fb
Revises: fcfc946b56c9
Create Date: 2024-06-13 20:44:46.175209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a6d035ec9fb'
down_revision: Union[str, None] = 'fcfc946b56c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('aspect_ratio', sa.Float(precision=4), nullable=True))
    op.alter_column('images', 'resolution_ratio',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'resolution_ratio',
               existing_type=sa.String(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('images', 'aspect_ratio')
    # ### end Alembic commands ###
