"""Modified Image

Revision ID: 9aaebde265ca
Revises: 799bc67607bf
Create Date: 2024-07-07 09:58:34.215523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aaebde265ca'
down_revision: Union[str, None] = '799bc67607bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawlers', sa.Column('target_user_id', sa.String(), nullable=True))
    op.add_column('crawlers', sa.Column('target_start_date', sa.DateTime(), nullable=True))
    op.add_column('crawlers', sa.Column('target_end_date', sa.DateTime(), nullable=True))
    op.add_column('crawlers', sa.Column('target_search_prompt', sa.String(), nullable=True))
    op.add_column('images', sa.Column('downloaded', sa.Boolean(), nullable=True))
    op.add_column('images', sa.Column('processed', sa.Boolean(), nullable=True))
    op.alter_column('images', 'aspect_ratio',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'aspect_ratio',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_column('images', 'processed')
    op.drop_column('images', 'downloaded')
    op.drop_column('crawlers', 'target_search_prompt')
    op.drop_column('crawlers', 'target_end_date')
    op.drop_column('crawlers', 'target_start_date')
    op.drop_column('crawlers', 'target_user_id')
    # ### end Alembic commands ###
