"""Add w&h

Revision ID: e75db90636c5
Revises: 9a6d035ec9fb
Create Date: 2024-06-14 23:10:15.397620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e75db90636c5'
down_revision: Union[str, None] = '9a6d035ec9fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('images', sa.Column('height', sa.Integer(), nullable=True))
    op.alter_column('images', 'aspect_ratio',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=True)
    op.drop_column('images', 'resolution_ratio')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('resolution_ratio', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('images', 'aspect_ratio',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_column('images', 'height')
    op.drop_column('images', 'width')
    # ### end Alembic commands ###
