"""Add resolution_ratio & colours

Revision ID: fcfc946b56c9
Revises: 56a1d53fa757
Create Date: 2024-06-13 18:20:44.567670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcfc946b56c9'
down_revision: Union[str, None] = '56a1d53fa757'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('resolution_ratio', sa.JSON(), nullable=True))
    op.add_column('images', sa.Column('colours', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'colours')
    op.drop_column('images', 'resolution_ratio')
    # ### end Alembic commands ###
